name: SMonitor
version: 1.0.0
author: solo
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\smonitor\SMonitor
commands:
  작업관리자:
    description: 작업관리자를 켭니다
    permission: smonitor.command.monitor

permissions:
  smonitor:
    default: op
    children:
      smonitor.command:
        default: op
        children:
          smonitor.command.monitor:
            default: op
